apiVersion: v1
kind: Service
metadata:
  name: service_mesh
  labels:
    app: service_mesh
spec:
  selector:
    app: service_mesh
  ports:
  - protocol: TCP
    port: 3145
    targetPort: 3145
  type: ClusterIP
