apiVersion: v1
kind: Service
metadata:
  name: api_gateway
  labels:
    app: api_gateway
spec:
  selector:
    app: api_gateway
  ports:
  - protocol: TCP
    port: 3208
    targetPort: 3208
  type: ClusterIP
