apiVersion: v1
kind: Service
metadata:
  name: haritaoza-com
  namespace: platform
  labels:
    app: haritaoza-com
    atlasos.io/managed: "true"
spec:
  selector:
    app: haritaoza-com
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP
