apiVersion: v1
kind: Service
metadata:
  name: lis-1-0-mvc
  namespace: platform
  labels:
    app: lis-1-0-mvc
    atlasos.io/managed: "true"
spec:
  selector:
    app: lis-1-0-mvc
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP
