apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clinical-postgres
  namespace: medinovai-clinical
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: clinical-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_URL
      remoteRef:
        key: infra/postgres-clinical
        property: POSTGRES_URL
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: infra/postgres-clinical
        property: POSTGRES_PASSWORD
