apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clinical-secrets
  namespace: clinical
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: clinical-secrets
    creationPolicy: Owner
  data:
    - secretKey: FHIR_SERVER_SECRET
      remoteRef:
        key: clinical/fhir-server
        property: secret
    - secretKey: CTMS_DB_URL
      remoteRef:
        key: clinical/ctms-db
        property: url
    - secretKey: POSTGRES_CLINICAL_URL
      remoteRef:
        key: infra/postgres-clinical
        property: url
    - secretKey: JWT_SIGNING_KEY
      remoteRef:
        key: security/jwt-signing
        property: private_key
