apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret-store.yaml
  - external-secret-infra.yaml
  - external-secret-atlasos.yaml
  - external-secret-security.yaml
  - external-secret-platform.yaml
  - external-secret-ai-ml.yaml
  - external-secret-clinical.yaml
