#!/usr/bin/env bash
# ─── deployer-entrypoint.sh ───────────────────────────────────────────────────
# Runs inside the medinovai-deployer container. Two phases:
#
# Phase 1 — Bootstrap (runs once, idempotent):
#   Installs Atlas, writes config and workspace files into named volumes,
#   writes sentinel file to unblock downstream services.
#
# Phase 2 — Watchdog (runs forever after bootstrap):
#   Every  5 min: health check all services, POST results to medinovaiOS
#   Every 60 min: drift check (k8s manifest vs cluster state)
#   Every 24 hrs: database backup + certificate expiry check
#
# Volumes expected:
#   /atlas-home        → atlas-config  (atlas.json + .env + workspaces)
#   /atlas-workspaces  → atlas-workspaces (agent workspace dirs)
#   /atlas-ui-built    → atlas-ui-source  (built Next.js output for atlas-ui)
#
# Sentinel file: /atlas-home/.deploy-complete
#   Written on bootstrap success — Docker healthcheck reads this to unblock
#   downstream services. The watchdog loop runs regardless of sentinel state.
#
# Idempotency: if the sentinel already exists, bootstrap is skipped and the
#   container jumps directly to the watchdog loop.
#   To force re-bootstrap: remove the atlas-config volume and re-run compose up.
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

ATLAS_HOME="${ATLAS_HOME:-/atlas-home}"
ATLAS_WORKSPACES="${ATLAS_WORKSPACES:-/atlas-workspaces}"
ATLAS_UI_OUT="${ATLAS_UI_OUT:-/atlas-ui-built}"
SENTINEL="$ATLAS_HOME/.deploy-complete"
REPO_ROOT="/repo"

# Watchdog interval overrides (seconds) — set via env for testing
HEALTH_INTERVAL="${WATCHDOG_HEALTH_INTERVAL:-300}"       # 5 min
DRIFT_INTERVAL="${WATCHDOG_DRIFT_INTERVAL:-3600}"        # 60 min
BACKUP_INTERVAL="${WATCHDOG_BACKUP_INTERVAL:-86400}"     # 24 hr
MEDINOVAIOS_URL="${MEDINOVAIOS_URL:-http://medinovaios:3030}"

# ── Colours ───────────────────────────────────────────────────────────────────
G="\033[0;32m"; Y="\033[1;33m"; R="\033[0;31m"; B="\033[0;34m"; NC="\033[0m"; BOLD="\033[1m"
log()  { echo -e "${G}[deployer]${NC} $(date -u '+%H:%M:%S') $*"; }
step() { echo -e "\n${BOLD}${B}━━━ $* ━━━${NC}"; }
warn() { echo -e "${Y}[deployer]${NC} $(date -u '+%H:%M:%S') $*"; }
err()  { echo -e "${R}[deployer]${NC} $(date -u '+%H:%M:%S') $*" >&2; }
ok()   { echo -e "${G}  ✓${NC} $*"; }

echo ""
echo -e "${BOLD}${G}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${G}║  MedinovAI Deploy Agent — Bootstrap + Watchdog          ║${NC}"
echo -e "${BOLD}${G}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
log "ATLAS_HOME       = $ATLAS_HOME"
log "ATLAS_WORKSPACES = $ATLAS_WORKSPACES"
log "ATLAS_UI_OUT     = $ATLAS_UI_OUT"
log "Health interval  = ${HEALTH_INTERVAL}s"
log "Drift interval   = ${DRIFT_INTERVAL}s"
log "Backup interval  = ${BACKUP_INTERVAL}s"
echo ""

# ── Idempotency check — skip bootstrap, go straight to watchdog ──────────────
if [ -f "$SENTINEL" ]; then
    log "Sentinel found at $SENTINEL — bootstrap already complete. Entering watchdog."
    # Jump directly to watchdog (defined below)
fi

# ── Step 1: Ensure volume directories exist ───────────────────────────────────
step "1 / 5  Prepare volume directories"
mkdir -p "$ATLAS_HOME" "$ATLAS_WORKSPACES" "$ATLAS_UI_OUT"
ok "Volume directories ready"

# ── Step 2: Install Atlas CLI ─────────────────────────────────────────────────
step "2 / 5  Install Atlas CLI"
if command -v atlas &>/dev/null; then
    ok "Atlas already installed: $(atlas --version 2>/dev/null || echo 'unknown version')"
else
    log "Installing atlas@latest via npm..."
    npm install -g atlas@latest --silent
    if ! command -v atlas &>/dev/null; then
        err "atlas command not found after install — check npm global bin path"
        exit 1
    fi
    ok "Atlas installed: $(atlas --version 2>/dev/null || echo 'ok')"
fi

# ── Step 3: Deploy config + workspaces into volume ───────────────────────────
step "3 / 5  Deploy config + workspaces (ATLAS_HOME=$ATLAS_HOME)"

# Point deploy_config.sh at the volume (not ~/.atlas/).
# The script already respects ${ATLAS_HOME} after the fix in scripts/deploy/deploy_config.sh.
export ATLAS_HOME
bash "$REPO_ROOT/scripts/deploy/deploy_config.sh"

# Write .env from injected environment variables (never commit real values).
ENV_FILE="$ATLAS_HOME/.env"
log "Writing $ENV_FILE from environment..."
cat > "$ENV_FILE" <<EOF
# Generated by medinovai-deployer at $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT commit this file — it contains live secrets.

SLACK_APP_TOKEN=${SLACK_APP_TOKEN:-}
SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN:-}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
HOOKS_TOKEN=${HOOKS_TOKEN:-}

# Ollama — points at the sibling ollama container inside the compose stack
OLLAMA_BASE_URL=http://ollama:11434
OLLAMA_DEFAULT_MODEL=${OLLAMA_DEFAULT_MODEL:-qwen2.5:1.5b}

# Optional integrations
CRM_API_KEY=${CRM_API_KEY:-}
TICKETS_API_KEY=${TICKETS_API_KEY:-}
PAGERDUTY_API_KEY=${PAGERDUTY_API_KEY:-}
LINEAR_API_KEY=${LINEAR_API_KEY:-}
EOF
ok ".env written"

# ── Step 4: Build Atlas UI (if source is available) ───────────────────────────
step "4 / 5  Build Atlas UI"

ATLAS_UI_SRC="${ATLAS_UI_SRC:-}"

if [ -n "$ATLAS_UI_SRC" ] && [ -d "$ATLAS_UI_SRC" ]; then
    log "Atlas UI source found at $ATLAS_UI_SRC — building..."
    cp -r "$ATLAS_UI_SRC/." "$ATLAS_UI_OUT/"
    cd "$ATLAS_UI_OUT"
    if [ -f "package.json" ]; then
        npm ci --silent
        npm run build
        ok "Atlas UI built into $ATLAS_UI_OUT"
    else
        warn "No package.json in UI source — skipping build"
    fi
    cd "$REPO_ROOT"
elif [ -d "/atlas-ui-src" ]; then
    log "Atlas UI source found at /atlas-ui-src (volume mount) — building..."
    cp -r /atlas-ui-src/. "$ATLAS_UI_OUT/"
    cd "$ATLAS_UI_OUT"
    if [ -f "package.json" ]; then
        npm ci --silent
        npm run build
        ok "Atlas UI built into $ATLAS_UI_OUT"
    else
        warn "No package.json in /atlas-ui-src — skipping build"
    fi
    cd "$REPO_ROOT"
else
    warn "No Atlas UI source available (ATLAS_UI_SRC not set, /atlas-ui-src not mounted)."
    warn "atlas-ui service will not start. Mount the UI source or set ATLAS_UI_SRC."
fi

# ── Step 5: Write sentinel ─────────────────────────────────────────────────────
step "5 / 5  Finalise"

TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
cat > "$SENTINEL" <<EOF
{
  "status": "ok",
  "bootstrapped_at": "$TIMESTAMP",
  "atlas_home": "$ATLAS_HOME",
  "atlas_workspaces": "$ATLAS_WORKSPACES"
}
EOF
ok "Sentinel written: $SENTINEL"

echo ""
echo -e "${BOLD}${G}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${G}║  Bootstrap complete — entering watchdog loop             ║${NC}"
echo -e "${BOLD}${G}║  Downstream services unblocked (depends_on: healthy).   ║${NC}"
echo -e "${BOLD}${G}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
log "Bootstrap done at $TIMESTAMP"

# ── Watchdog Loop ─────────────────────────────────────────────────────────────
# Runs permanently after bootstrap. Never exits (container restart: unless-stopped).
# ─────────────────────────────────────────────────────────────────────────────

run_health_check() {
    log "[watchdog] Running health check..."
    HEALTH_OUTPUT=$(bash "$REPO_ROOT/scripts/monitoring/health_check_all.sh" 2>&1 || true)
    log "[watchdog] Health check complete."

    # POST summary to medinovaiOS health-push endpoint (best-effort, non-blocking)
    HEALTH_TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    HEALTH_SUMMARY=$(echo "$HEALTH_OUTPUT" | tail -20 | sed 's/"/\\"/g' | tr '\n' ' ')
    curl -sf -X POST "$MEDINOVAIOS_URL/api/health-push" \
        -H "Content-Type: application/json" \
        -d "{\"timestamp\":\"$HEALTH_TIMESTAMP\",\"source\":\"deploy-agent\",\"output\":\"$HEALTH_SUMMARY\"}" \
        --max-time 5 2>/dev/null || true
}

run_drift_check() {
    log "[watchdog] Running drift check..."
    bash "$REPO_ROOT/scripts/maintenance/drift_check.sh" 2>&1 || true
    log "[watchdog] Drift check complete."
}

run_backup() {
    log "[watchdog] Running scheduled database backup..."
    bash "$REPO_ROOT/scripts/maintenance/db_backup.sh" 2>/dev/null || true
    log "[watchdog] Backup complete."

    log "[watchdog] Checking certificate expiry..."
    bash "$REPO_ROOT/scripts/maintenance/cert_renewal.sh" --check-only 2>/dev/null || true
}

LAST_DRIFT_CHECK=0
LAST_BACKUP=0

log "[watchdog] Entering permanent watchdog loop (health every ${HEALTH_INTERVAL}s, drift every ${DRIFT_INTERVAL}s, backup every ${BACKUP_INTERVAL}s)"

while true; do
    NOW=$(date +%s)

    # Health check every HEALTH_INTERVAL seconds
    run_health_check

    # Drift check every DRIFT_INTERVAL seconds
    if (( NOW - LAST_DRIFT_CHECK >= DRIFT_INTERVAL )); then
        run_drift_check
        LAST_DRIFT_CHECK=$(date +%s)
    fi

    # Backup + cert check every BACKUP_INTERVAL seconds
    if (( NOW - LAST_BACKUP >= BACKUP_INTERVAL )); then
        run_backup
        LAST_BACKUP=$(date +%s)
    fi

    log "[watchdog] Sleeping ${HEALTH_INTERVAL}s..."
    sleep "$HEALTH_INTERVAL"
done
