#!/usr/bin/env python3
"""Generate docker-compose.all-services.yml from config/dependency-graph.json.

Reads the dependency graph and produces a single Docker Compose file that starts
all deployable MedinovAI services (tiers 1-6) against the platform network.
Tier 0 infrastructure is NOT included — it is managed by docker-compose.tier0
or docker-compose.dev.yml and must be running first.

Usage:
    python3 scripts/deploy/generate_all_services_compose.py
    python3 scripts/deploy/generate_all_services_compose.py --dry-run
    python3 scripts/deploy/generate_all_services_compose.py --tier 4
"""

import json
import sys
import os
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
DEPENDENCY_GRAPH = PROJECT_ROOT / "config" / "dependency-graph.json"
OUTPUT_FILE = PROJECT_ROOT / "infra" / "docker" / "docker-compose.all-services.yml"

SKIP_TYPES = {"infrastructure", "monitoring", "npm-publish", "config-only"}
SKIP_PORT = {None, "None", ""}
SKIP_SERVICE_IDS = {"medinovaios", "medinovai-aifactory"}

PORT_BASE = {
    "tier1": 10001,
    "tier2": 10100,
    "tier3": 10200,
    "tier4": 10300,
    "tier5": 10400,
    "tier6": 10500,
}

ML_SERVICE_TYPES = {"ml-service"}


def load_graph():
    with open(DEPENDENCY_GRAPH) as f:
        return json.load(f)


def collect_services(graph, tier_filter=None):
    """Collect all deployable services from the dependency graph."""
    services = []
    for tier_key, tier_data in sorted(graph["tiers"].items()):
        if tier_filter and tier_key != f"tier{tier_filter}":
            continue
        if tier_key == "tier0":
            continue

        tier_services = []
        for svc in tier_data.get("services", []):
            tier_services.append((tier_key, svc))
        for group_key, group_data in tier_data.get("sub_groups", {}).items():
            for svc in group_data.get("services", []):
                tier_services.append((tier_key, svc))

        services.extend(tier_services)
    return services


def sanitize_name(name):
    """Sanitize service ID for Docker Compose service name and image tag (must be lowercase)."""
    import re
    name = name.lower()
    name = name.replace(".", "-").replace("_", "-")
    name = re.sub(r"[^a-z0-9-]", "-", name)
    name = re.sub(r"-+", "-", name)
    return name.strip("-")


def generate_compose(graph, tier_filter=None):
    services = collect_services(graph, tier_filter)

    header = (
        "# Auto-generated by scripts/deploy/generate_all_services_compose.py\n"
        "# DO NOT EDIT — regenerate with: make generate-all-services\n"
        f"# Services: {len([s for _, s in services if str(s.get('port', '')) not in SKIP_PORT and s.get('type') not in SKIP_TYPES])}\n"
        f"# Source: config/dependency-graph.json v{graph.get('version', '?')}\n"
        "\n"
    )

    lines = [header]
    lines.append("services:\n")

    port_counters = dict(PORT_BASE)
    svc_count = 0

    for tier_key, svc in services:
        svc_id = svc.get("id", "")
        svc_type = svc.get("type", "python-service")
        svc_port = svc.get("port")
        health_path = svc.get("health", "/health")

        if svc_id in SKIP_SERVICE_IDS:
            continue
        if svc_type in SKIP_TYPES:
            continue
        if str(svc_port) in SKIP_PORT:
            continue

        svc_port = int(svc_port)
        svc_name = sanitize_name(svc_id)

        host_port = port_counters.get(tier_key, 10000)
        port_counters[tier_key] = host_port + 1

        is_ml = svc_type in ML_SERVICE_TYPES
        mem_limit = "2g" if is_ml else "512m"
        cpu_limit = "2.0" if is_ml else "0.5"
        mem_request = "256m" if is_ml else "64m"
        cpu_request = "0.2" if is_ml else "0.05"

        lines.append(f"  {svc_name}:\n")
        lines.append(f"    image: {svc_name}:latest\n")
        lines.append(f"    pull_policy: never\n")
        lines.append(f"    container_name: {svc_name}\n")
        lines.append(f"    ports:\n")
        lines.append(f'      - "{host_port}:{svc_port}"\n')
        lines.append(f"    environment:\n")
        lines.append(f'      SERVICE_NAME: "{svc_id}"\n')
        lines.append(f'      PORT: "{svc_port}"\n')
        lines.append(f'      REGISTRY_URL: "http://medinovai-registry:8080"\n')
        lines.append(f'      VAULT_ADDR: "http://medinovai-vault:8200"\n')
        lines.append(f'      VAULT_TOKEN: "${{VAULT_DEV_ROOT_TOKEN:-medinovai-dev-token}}"\n')
        lines.append(f'      DATABASE_URL: "postgresql://medinovai:${{POSTGRES_PASSWORD:-localdev}}@medinovai-postgres:5432/medinovai_main"\n')
        lines.append(f'      REDIS_URL: "redis://:${{REDIS_PASSWORD:-localdev}}@medinovai-redis:6379"\n')
        lines.append(f"    healthcheck:\n")
        lines.append(f'      test: ["CMD-SHELL", "curl -sf http://localhost:{svc_port}{health_path} || exit 1"]\n')
        lines.append(f"      interval: 30s\n")
        lines.append(f"      timeout: 10s\n")
        lines.append(f"      retries: 3\n")
        lines.append(f"      start_period: 30s\n")
        lines.append(f"    deploy:\n")
        lines.append(f"      resources:\n")
        lines.append(f"        limits:\n")
        lines.append(f"          memory: {mem_limit}\n")
        lines.append(f"          cpus: '{cpu_limit}'\n")
        lines.append(f"        reservations:\n")
        lines.append(f"          memory: {mem_request}\n")
        lines.append(f"          cpus: '{cpu_request}'\n")
        lines.append(f"    restart: unless-stopped\n")
        lines.append(f"    networks:\n")
        lines.append(f"      - medinovai-platform\n")
        lines.append(f"\n")
        svc_count += 1

    lines.append("networks:\n")
    lines.append("  medinovai-platform:\n")
    lines.append("    external: true\n")
    lines.append("    name: medinovai-dev_medinovai-dev\n")

    return "".join(lines), svc_count


def main():
    dry_run = "--dry-run" in sys.argv
    tier_filter = None
    if "--tier" in sys.argv:
        idx = sys.argv.index("--tier")
        tier_filter = sys.argv[idx + 1]

    if not DEPENDENCY_GRAPH.exists():
        print(f"ERROR: Dependency graph not found: {DEPENDENCY_GRAPH}")
        sys.exit(1)

    graph = load_graph()
    content, count = generate_compose(graph, tier_filter)

    if dry_run:
        print(content)
        print(f"\n# Would generate {count} services to {OUTPUT_FILE}")
    else:
        OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
        with open(OUTPUT_FILE, "w") as f:
            f.write(content)
        print(f"Generated {OUTPUT_FILE} with {count} services")


if __name__ == "__main__":
    main()
