apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medinovai-services

resources:
  - clinical-services.yaml
  - diagnostic-services.yaml
  - ai-services.yaml
  - medication-services.yaml
  - research-services.yaml
  - business-services.yaml
  - lis-services.yaml
