apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-inference
  namespace: medinovai-ai
spec:
  template:
    spec:
      containers:
        - name: ai-inference
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
