apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: medinovai-ai-local
  labels:
    app: ollama
spec:
  selector:
    app: ollama
  ports:
    - name: http
      port: 11434
      targetPort: 11434
      nodePort: 31434
  type: NodePort
