apiVersion: v1
kind: Service
metadata:
  name: mayanktrivedi-1
  namespace: platform
  labels:
    app: mayanktrivedi-1
    atlasos.io/managed: "true"
spec:
  selector:
    app: mayanktrivedi-1
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP
