apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: org-azure-keyvault
spec:
  provider:
    azurekv:
      vaultUrl: https://your-vault-name.vault.azure.net
      authType: WorkloadIdentity
      serviceAccountRef:
        name: eso-azure
        namespace: external-secrets
