apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: org-gcp-secrets-manager
spec:
  provider:
    gcpsm:
      projectID: your-gcp-project
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: eso-gcp
            namespace: external-secrets
