apiVersion: v1
kind: Service
metadata:
  name: ctms-simulation
  namespace: platform
  labels:
    app: ctms-simulation
    atlasos.io/managed: "true"
spec:
  selector:
    app: ctms-simulation
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP
