apiVersion: v1
kind: Service
metadata:
  name: --docker-maintenance
  namespace: platform
  labels:
    app: --docker-maintenance
    atlasos.io/managed: "true"
spec:
  selector:
    app: --docker-maintenance
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP
