apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medinovai-security

resources:
  - secrets-manager-bridge.yaml
  - security.yaml
  - universal-sign-on.yaml
  - role-based-permissions.yaml
  - encryption-vault.yaml
  - hipaa-gdpr-guard.yaml
  - consent-preference-api.yaml
  - audit-trail-explorer.yaml
