#!/bin/bash
# MedinovAI Standards Migration Script
# Migrates repositories to comply with MedinovAI Comprehensive Standards v2.0.0

set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
TEMPLATES_DIR="$PROJECT_ROOT/templates"
BACKUP_DIR="$PROJECT_ROOT/migration-backups/$(date +%Y%m%d_%H%M%S)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Create backup directory
create_backup() {
    local repo_path="$1"
    local repo_name=$(basename "$repo_path")
    local backup_path="$BACKUP_DIR/$repo_name"
    
    log_info "Creating backup for $repo_name..."
    mkdir -p "$backup_path"
    cp -r "$repo_path" "$backup_path/"
    log_success "Backup created at $backup_path"
}

# Update Dockerfile to use MedinovAI base image
update_dockerfile() {
    local repo_path="$1"
    local dockerfile_path="$repo_path/Dockerfile"
    
    log_info "Updating Dockerfile for $(basename "$repo_path")..."
    
    if [ -f "$dockerfile_path" ]; then
        # Backup original Dockerfile
        cp "$dockerfile_path" "$dockerfile_path.backup"
        
        # Create new Dockerfile with MedinovAI standards
        cat > "$dockerfile_path" << 'EOF'
# MedinovAI Standards Compliant Dockerfile
# Generated by MedinovAI Standards Migration Script

FROM medinovai/base:latest

# Security: Run as non-root user
USER medinovai:medinovai

# Set working directory
WORKDIR /app

# Copy application code
COPY --chown=medinovai:medinovai . /app

# Install Python dependencies (if requirements.txt exists)
RUN if [ -f requirements.txt ]; then \
        pip install --no-cache-dir --user -r requirements.txt; \
    fi

# Install Node.js dependencies (if package.json exists)
RUN if [ -f package.json ]; then \
        npm ci --only=production; \
    fi

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD curl -f http://localhost:8080/health || exit 1

# Expose port
EXPOSE 8080

# Start application
CMD ["python", "app.py"]
EOF
        
        log_success "Dockerfile updated"
    else
        log_warning "No Dockerfile found, creating new one..."
        cp "$TEMPLATES_DIR/dockerfile-standards/Dockerfile" "$dockerfile_path"
    fi
}

# Create .medinovai directory structure
create_medinovai_config() {
    local repo_path="$1"
    local medinovai_dir="$repo_path/.medinovai"
    
    log_info "Creating .medinovai configuration for $(basename "$repo_path")..."
    
    mkdir -p "$medinovai_dir"
    
    # Create standards.yml
    cat > "$medinovai_dir/standards.yml" << EOF
# MedinovAI Repository Standards Configuration
# Generated by MedinovAI Standards Migration Script

repository:
  name: "$(basename "$repo_path")"
  type: "service"
  version: "1.0.0"
  
standards:
  registry_integration: true
  data_services_required: true
  security_level: "high"
  performance_target: "sub-second"
  
timeouts:
  dynamic: true
  base_timeout: 300
  max_timeout: 1800
  min_timeout: 60
  
monitoring:
  health_checks: true
  metrics_collection: true
  logging_level: "INFO"
  
compliance:
  hipaa: true
  gdpr: true
  soc2: true
  fda: false
EOF

    # Create registry-config.yml
    cat > "$medinovai_dir/registry-config.yml" << EOF
# MedinovAI Registry Integration Configuration
# Generated by MedinovAI Standards Migration Script

registry:
  name: "medinovai-registry"
  url: "https://registry.medinovai.com"
  namespace: "medinovai"
  
images:
  base_image: "medinovai/base:latest"
  security_scan: true
  vulnerability_check: true
  
build:
  multi_stage: true
  optimization: true
  cache_strategy: "layer"
  
deployment:
  auto_deploy: false
  approval_required: true
  rollback_enabled: true
EOF

    # Create data-services-config.yml
    cat > "$medinovai_dir/data-services-config.yml" << EOF
# MedinovAI Data Services Integration Configuration
# Generated by MedinovAI Standards Migration Script

data_services:
  required: true
  endpoint: "https://data-services.medinovai.com"
  authentication: "oauth2"
  
data_operations:
  read_only: false
  write_operations: true
  batch_operations: true
  
compliance:
  encryption_at_rest: true
  encryption_in_transit: true
  audit_logging: true
  
performance:
  connection_pooling: true
  caching_enabled: true
  timeout_dynamic: true
EOF

    log_success ".medinovai configuration created"
}

# Add CI/CD workflows
add_cicd_workflows() {
    local repo_path="$1"
    local workflows_dir="$repo_path/.github/workflows"
    
    log_info "Adding CI/CD workflows for $(basename "$repo_path")..."
    
    mkdir -p "$workflows_dir"
    
    # Create CI workflow
    cat > "$workflows_dir/ci.yml" << EOF
name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v
    
    - name: Run linting
      run: |
        flake8 src/
        black --check src/
    
    - name: Security scan
      run: |
        bandit -r src/
        safety check

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        docker build -t medinovai/$(basename "$repo_path"):latest .
    
    - name: Security scan
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \\
          aquasec/trivy image medinovai/$(basename "$repo_path"):latest
EOF

    # Create CD workflow
    cat > "$workflows_dir/cd.yml" << EOF
name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and push to registry
      run: |
        echo \${{ secrets.REGISTRY_TOKEN }} | docker login medinovai-registry.com -u \${{ secrets.REGISTRY_USERNAME }} --password-stdin
        docker build -t medinovai/$(basename "$repo_path"):\${{ github.sha }} .
        docker push medinovai/$(basename "$repo_path"):\${{ github.sha }}
        docker push medinovai/$(basename "$repo_path"):latest
    
    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/$(basename "$repo_path") $(basename "$repo_path")=medinovai/$(basename "$repo_path"):\${{ github.sha }}
EOF

    # Create standards validation workflow
    cat > "$workflows_dir/standards-validation.yml" << EOF
name: Standards Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate-standards:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate MedinovAI Standards
      run: |
        python scripts/validate-standards.py
    
    - name: Check registry integration
      run: |
        test -f .medinovai/registry-config.yml
        test -f .medinovai/data-services-config.yml
        test -f .medinovai/standards.yml
    
    - name: Validate Dockerfile
      run: |
        docker run --rm -i hadolint/hadolint < Dockerfile
EOF

    log_success "CI/CD workflows added"
}

# Add health check endpoint
add_health_check() {
    local repo_path="$1"
    local src_dir="$repo_path/src"
    
    log_info "Adding health check endpoint for $(basename "$repo_path")..."
    
    mkdir -p "$src_dir"
    
    # Create health check module
    cat > "$src_dir/health.py" << EOF
"""
MedinovAI Health Check Module
Compliant with MedinovAI Standards v2.0.0
"""

import time
import psutil
from datetime import datetime
from typing import Dict, Any
from medinovai_monitoring import HealthChecker

class ServiceHealthChecker(HealthChecker):
    def __init__(self, service_name: str):
        super().__init__()
        self.service_name = service_name
        self.start_time = time.time()
    
    def check_health(self) -> Dict[str, Any]:
        """Comprehensive health check"""
        health_status = {
            "status": "healthy",
            "timestamp": datetime.utcnow().isoformat(),
            "service": self.service_name,
            "uptime": time.time() - self.start_time,
            "checks": {}
        }
        
        # Check system resources
        health_status["checks"]["system"] = self._check_system_resources()
        
        # Check service dependencies
        health_status["checks"]["dependencies"] = self._check_dependencies()
        
        # Determine overall status
        if any(check["status"] != "healthy" for check in health_status["checks"].values()):
            health_status["status"] = "unhealthy"
        
        return health_status
    
    def _check_system_resources(self) -> Dict[str, Any]:
        """Check system resource usage"""
        try:
            cpu_percent = psutil.cpu_percent(interval=1)
            memory = psutil.virtual_memory()
            
            return {
                "status": "healthy" if cpu_percent < 90 and memory.percent < 90 else "warning",
                "cpu_usage": cpu_percent,
                "memory_usage": memory.percent,
                "available_memory": memory.available
            }
        except Exception as e:
            return {
                "status": "error",
                "error": str(e)
            }
    
    def _check_dependencies(self) -> Dict[str, Any]:
        """Check service dependencies"""
        # This should be implemented based on specific service dependencies
        return {
            "status": "healthy",
            "dependencies": []
        }
EOF

    log_success "Health check endpoint added"
}

# Add monitoring configuration
add_monitoring_config() {
    local repo_path="$1"
    local monitoring_dir="$repo_path/monitoring"
    
    log_info "Adding monitoring configuration for $(basename "$repo_path")..."
    
    mkdir -p "$monitoring_dir"
    
    # Create Prometheus configuration
    cat > "$monitoring_dir/prometheus.yml" << EOF
# MedinovAI Prometheus Configuration
# Generated by MedinovAI Standards Migration Script

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: '$(basename "$repo_path")'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
EOF

    # Create Grafana dashboard
    cat > "$monitoring_dir/dashboard.json" << EOF
{
  "dashboard": {
    "title": "$(basename "$repo_path") Dashboard",
    "panels": [
      {
        "title": "Request Rate",
        "type": "graph",
        "targets": [
          {
            "expr": "rate(http_requests_total[5m])",
            "legendFormat": "Requests/sec"
          }
        ]
      },
      {
        "title": "Response Time",
        "type": "graph",
        "targets": [
          {
            "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
            "legendFormat": "95th percentile"
          }
        ]
      }
    ]
  }
}
EOF

    log_success "Monitoring configuration added"
}

# Main migration function
migrate_repository() {
    local repo_path="$1"
    local repo_name=$(basename "$repo_path")
    
    log_info "Starting migration for repository: $repo_name"
    
    # Validate repository path
    if [ ! -d "$repo_path" ]; then
        log_error "Repository path does not exist: $repo_path"
        return 1
    fi
    
    # Create backup
    create_backup "$repo_path"
    
    # Apply migrations
    create_medinovai_config "$repo_path"
    update_dockerfile "$repo_path"
    add_cicd_workflows "$repo_path"
    add_health_check "$repo_path"
    add_monitoring_config "$repo_path"
    
    log_success "Migration completed for: $repo_name"
}

# Validate migration
validate_migration() {
    local repo_path="$1"
    local repo_name=$(basename "$repo_path")
    
    log_info "Validating migration for: $repo_name"
    
    local validation_passed=true
    
    # Check required files
    local required_files=(
        ".medinovai/standards.yml"
        ".medinovai/registry-config.yml"
        ".medinovai/data-services-config.yml"
        ".github/workflows/ci.yml"
        ".github/workflows/cd.yml"
        ".github/workflows/standards-validation.yml"
        "Dockerfile"
        "src/health.py"
    )
    
    for file in "${required_files[@]}"; do
        if [ ! -f "$repo_path/$file" ]; then
            log_error "Missing required file: $file"
            validation_passed=false
        fi
    done
    
    if [ "$validation_passed" = true ]; then
        log_success "Migration validation passed for: $repo_name"
    else
        log_error "Migration validation failed for: $repo_name"
    fi
    
    return $([ "$validation_passed" = true ] && echo 0 || echo 1)
}

# Main execution
main() {
    log_info "MedinovAI Standards Migration Script v2.0.0"
    log_info "Starting migration process..."
    
    # Create backup directory
    mkdir -p "$BACKUP_DIR"
    log_info "Backup directory created: $BACKUP_DIR"
    
    # Find all MedinovAI repositories
    local repos_found=0
    local repos_migrated=0
    local repos_failed=0
    
    for repo in /Users/dev1/github/medinovai-*; do
        if [ -d "$repo" ]; then
            repos_found=$((repos_found + 1))
            log_info "Found repository: $(basename "$repo")"
            
            if migrate_repository "$repo"; then
                if validate_migration "$repo"; then
                    repos_migrated=$((repos_migrated + 1))
                else
                    repos_failed=$((repos_failed + 1))
                fi
            else
                repos_failed=$((repos_failed + 1))
            fi
        fi
    done
    
    # Summary
    log_info "Migration Summary:"
    log_info "  Repositories found: $repos_found"
    log_info "  Successfully migrated: $repos_migrated"
    log_info "  Failed migrations: $repos_failed"
    log_info "  Backup location: $BACKUP_DIR"
    
    if [ $repos_failed -eq 0 ]; then
        log_success "All repositories migrated successfully!"
        exit 0
    else
        log_error "Some migrations failed. Check logs for details."
        exit 1
    fi
}

# Run main function
main "$@"

