# syntax=docker/dockerfile:1.7
FROM cgr.dev/chainguard/static:latest as base
# Add your binary/app here; this is a safe minimal base.
# COPY build/myapp /usr/local/bin/myapp
ENTRYPOINT ["sh","-c","echo replace with your app && sleep 1d"]
