# ─── Vault Policies for MedinovAI Platform ───────────────────────────────────
# Apply with: vault policy write <name> policies.hcl (filtered per section)

# ─── infra-admin: Full access to infrastructure secrets ──────────────────────
# path "medinovai-secrets/data/infra/*" { capabilities = ["create", "read", "update", "delete", "list"] }
# path "medinovai-secrets/metadata/infra/*" { capabilities = ["list", "read", "delete"] }

# ─── atlasos-read: AtlasOS services read their own secrets ──────────────────
# path "medinovai-secrets/data/atlasos/*" { capabilities = ["read"] }
# path "medinovai-secrets/metadata/atlasos/*" { capabilities = ["list", "read"] }

# ─── platform-read: Platform core services ──────────────────────────────────
# path "medinovai-secrets/data/platform/*" { capabilities = ["read"] }
# path "medinovai-secrets/metadata/platform/*" { capabilities = ["list", "read"] }

# ─── security-read: Security tier services ──────────────────────────────────
# path "medinovai-secrets/data/security/*" { capabilities = ["read"] }
# path "medinovai-secrets/metadata/security/*" { capabilities = ["list", "read"] }

# ─── clinical-read: Clinical services (PHI-adjacent) ────────────────────────
# path "medinovai-secrets/data/clinical/*" { capabilities = ["read"] }
# path "medinovai-secrets/metadata/clinical/*" { capabilities = ["list", "read"] }

# ─── ai-ml-read: AI/ML services ────────────────────────────────────────────
# path "medinovai-secrets/data/ai-ml/*" { capabilities = ["read"] }
# path "medinovai-secrets/metadata/ai-ml/*" { capabilities = ["list", "read"] }

# Note: Individual policy files are generated by init-vault.sh
# This file documents the policy structure. Each section above becomes
# a separate .hcl file applied to Vault.
