apiVersion: v1
kind: Service
metadata:
  labels:
    app: medinovai-authentication
  name: medinovai-authentication
  namespace: medinovai
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: medinovai-authentication
  type: ClusterIP

