apiVersion: v1
kind: Service
metadata:
  name: descartesbio-in
  namespace: platform
  labels:
    app: descartesbio-in
    atlasos.io/managed: "true"
spec:
  selector:
    app: descartesbio-in
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP
