#!/usr/bin/env bash
# ─── init-secrets.sh ──────────────────────────────────────────────────────────
# Initialize secret management infrastructure and seed initial secrets.
#
# Usage:
#   bash scripts/bootstrap/init-secrets.sh --cloud aws --environment production
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

CLOUD="aws"
ENVIRONMENT="staging"
PROJECT="medinovai"
VAULT_ADDR="${VAULT_ADDR:-http://localhost:8200}"
VAULT_TOKEN="${VAULT_TOKEN:-${VAULT_DEV_ROOT_TOKEN:-medinovai-dev-token}}"

while [[ $# -gt 0 ]]; do
    case $1 in
        --cloud)        CLOUD="$2"; shift 2 ;;
        --environment)  ENVIRONMENT="$2"; shift 2 ;;
        --vault-addr)   VAULT_ADDR="$2"; shift 2 ;;
        *)              echo "Unknown option: $1"; exit 1 ;;
    esac
done

export VAULT_ADDR VAULT_TOKEN

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║       Secrets Initialization — $ENVIRONMENT                 ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

generate_password() {
    python3 -c "import secrets, string; print(secrets.token_urlsafe(32))"
}

generate_jwt_secret() {
    python3 -c "import secrets; print(secrets.token_hex(64))"
}

SECRET_PREFIX="${PROJECT}/${ENVIRONMENT}"

echo "▸ Generating secrets..."
DB_PASSWORD=$(generate_password)
REDIS_PASSWORD=$(generate_password)
JWT_SECRET=$(generate_jwt_secret)
API_KEY=$(generate_password)
ENCRYPTION_KEY=$(generate_password)

echo "  ✓ Database password generated"
echo "  ✓ Redis password generated"
echo "  ✓ JWT signing secret generated"
echo "  ✓ Internal API key generated"
echo "  ✓ Encryption key generated"

case "$CLOUD" in
    aws)
        echo ""
        echo "▸ Storing secrets in AWS Secrets Manager..."
        SECRETS=(
            "${SECRET_PREFIX}/database/password:$DB_PASSWORD"
            "${SECRET_PREFIX}/redis/password:$REDIS_PASSWORD"
            "${SECRET_PREFIX}/jwt/secret:$JWT_SECRET"
            "${SECRET_PREFIX}/api/internal-key:$API_KEY"
            "${SECRET_PREFIX}/encryption/key:$ENCRYPTION_KEY"
        )
        for entry in "${SECRETS[@]}"; do
            name="${entry%%:*}"
            value="${entry#*:}"
            echo "  Storing: $name"
            aws secretsmanager create-secret \
                --name "$name" \
                --secret-string "$value" \
                --description "Auto-generated by medinovai-deploy init-secrets" \
                2>/dev/null || \
            aws secretsmanager update-secret \
                --secret-id "$name" \
                --secret-string "$value" \
                2>/dev/null || \
            echo "  ⚠ Could not store $name (check permissions)"
        done
        ;;
    vault)
        echo ""
        echo "▸ Storing secrets in HashiCorp Vault (KV v2)..."
        echo "  Vault address: $VAULT_ADDR"

        # Ensure Vault is reachable
        if ! vault status -address="$VAULT_ADDR" &>/dev/null; then
            echo "  ERROR: Vault is not reachable at $VAULT_ADDR"
            echo "  Ensure the vault container is running: docker compose up -d vault"
            exit 1
        fi

        # Ensure KV v2 engine is enabled
        if ! vault secrets list -format=json 2>/dev/null | grep -q '"secret/"'; then
            vault secrets enable -path=secret kv-v2
            echo "  ✓ KV v2 secrets engine enabled"
        fi

        # Write generated secrets into Vault KV v2
        vault_put() {
            local path="$1"; shift
            vault kv put "secret/medinovai/$path" "$@" \
                && echo "  ✓ secret/medinovai/$path" \
                || echo "  ⚠ Failed to write secret/medinovai/$path"
        }

        vault_put "infra/postgres"       password="$DB_PASSWORD"
        vault_put "infra/redis"          password="$REDIS_PASSWORD"
        vault_put "infra/jwt"            secret="$JWT_SECRET"
        vault_put "infra/api-key"        key="$API_KEY"
        vault_put "infra/encryption"     key="$ENCRYPTION_KEY"
        ;;
    *)
        echo ""
        echo "▸ Secret storage for $CLOUD not yet implemented."
        echo "  Generated secrets are displayed below. Store them securely."
        echo ""
        echo "  DB_PASSWORD=$DB_PASSWORD"
        echo "  REDIS_PASSWORD=$REDIS_PASSWORD"
        echo "  JWT_SECRET=$JWT_SECRET"
        echo "  API_KEY=$API_KEY"
        echo "  ENCRYPTION_KEY=$ENCRYPTION_KEY"
        echo ""
        echo "  WARNING: These will not be displayed again!"
        ;;
esac

echo ""
echo "✓ Secrets initialization complete."
echo "  These secrets should be rotated within 90 days (or sooner per policy)."
