#!/usr/bin/env bash
# ─── init-secrets.sh ──────────────────────────────────────────────────────────
# Initialize secret management infrastructure and seed initial secrets.
#
# Usage:
#   bash scripts/bootstrap/init-secrets.sh --cloud aws --environment production
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

CLOUD="aws"
ENVIRONMENT="staging"
PROJECT="medinovai"

while [[ $# -gt 0 ]]; do
    case $1 in
        --cloud)        CLOUD="$2"; shift 2 ;;
        --environment)  ENVIRONMENT="$2"; shift 2 ;;
        *)              echo "Unknown option: $1"; exit 1 ;;
    esac
done

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║       Secrets Initialization — $ENVIRONMENT                 ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

generate_password() {
    python3 -c "import secrets, string; print(secrets.token_urlsafe(32))"
}

generate_jwt_secret() {
    python3 -c "import secrets; print(secrets.token_hex(64))"
}

SECRET_PREFIX="${PROJECT}/${ENVIRONMENT}"

echo "▸ Generating secrets..."
DB_PASSWORD=$(generate_password)
REDIS_PASSWORD=$(generate_password)
JWT_SECRET=$(generate_jwt_secret)
API_KEY=$(generate_password)
ENCRYPTION_KEY=$(generate_password)

echo "  ✓ Database password generated"
echo "  ✓ Redis password generated"
echo "  ✓ JWT signing secret generated"
echo "  ✓ Internal API key generated"
echo "  ✓ Encryption key generated"

case "$CLOUD" in
    aws)
        echo ""
        echo "▸ Storing secrets in AWS Secrets Manager..."
        SECRETS=(
            "${SECRET_PREFIX}/database/password:$DB_PASSWORD"
            "${SECRET_PREFIX}/redis/password:$REDIS_PASSWORD"
            "${SECRET_PREFIX}/jwt/secret:$JWT_SECRET"
            "${SECRET_PREFIX}/api/internal-key:$API_KEY"
            "${SECRET_PREFIX}/encryption/key:$ENCRYPTION_KEY"
        )
        for entry in "${SECRETS[@]}"; do
            name="${entry%%:*}"
            value="${entry#*:}"
            echo "  Storing: $name"
            aws secretsmanager create-secret \
                --name "$name" \
                --secret-string "$value" \
                --description "Auto-generated by medinovai-deploy init-secrets" \
                2>/dev/null || \
            aws secretsmanager update-secret \
                --secret-id "$name" \
                --secret-string "$value" \
                2>/dev/null || \
            echo "  ⚠ Could not store $name (check permissions)"
        done
        ;;
    *)
        echo ""
        echo "▸ Secret storage for $CLOUD not yet implemented."
        echo "  Generated secrets are displayed below. Store them securely."
        echo ""
        echo "  DB_PASSWORD=$DB_PASSWORD"
        echo "  REDIS_PASSWORD=$REDIS_PASSWORD"
        echo "  JWT_SECRET=$JWT_SECRET"
        echo "  API_KEY=$API_KEY"
        echo "  ENCRYPTION_KEY=$ENCRYPTION_KEY"
        echo ""
        echo "  WARNING: These will not be displayed again!"
        ;;
esac

echo ""
echo "✓ Secrets initialization complete."
echo "  These secrets should be rotated within 90 days (or sooner per policy)."
