#!/usr/bin/env bash
# ─── tailscale-config.sh ──────────────────────────────────────────────────────
# Configure MedinovAI for Tailscale-based multi-machine deployment.
#
# What it does:
#   - Detects this machine's Tailscale IP and hostname
#   - Designates which machine hosts postgres/redis (primary DB node)
#   - Writes .env.tailscale (gitignored, per-machine)
#   - Generates infra/kubernetes/overlays/docker-desktop/configmap-env-local.yaml
#   - Updates docker-compose.dev.yml to bind on 0.0.0.0 (Tailscale-reachable)
#
# Usage:
#   bash scripts/bootstrap/tailscale-config.sh
#   bash scripts/bootstrap/tailscale-config.sh --primary            # this machine is the DB primary
#   bash scripts/bootstrap/tailscale-config.sh --db-host 100.x.x.x # remote primary
#
# Run BEFORE install-k8s.sh on every machine.
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"
OVERLAY_DIR="$REPO_ROOT/infra/kubernetes/overlays/docker-desktop"
ENV_FILE="$REPO_ROOT/.env.tailscale"

IS_PRIMARY=false
DB_HOST_OVERRIDE=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --primary)            IS_PRIMARY=true; shift ;;
        --db-host)            DB_HOST_OVERRIDE="$2"; shift 2 ;;
        *)                    echo "Unknown option: $1"; exit 1 ;;
    esac
done

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  MedinovAI — Tailscale Configuration"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# ─── Detect Tailscale IP ──────────────────────────────────────────────────────
echo "▸ Detecting Tailscale..."
command -v tailscale &>/dev/null || { echo "  ✗ Tailscale not installed. Install from https://tailscale.com/download"; exit 1; }

TS_IP=$(tailscale ip --4 2>/dev/null || echo "")
TS_HOSTNAME=$(tailscale status --json 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('Self',{}).get('HostName','unknown'))" 2>/dev/null || hostname)
TS_MAGICHOST="${TS_HOSTNAME}"

if [ -z "$TS_IP" ]; then
    echo "  ✗ Tailscale not connected. Run: tailscale up"
    exit 1
fi

echo "  ✓ This machine: $TS_HOSTNAME @ $TS_IP"

# ─── Determine DB host ───────────────────────────────────────────────────────
if [ -n "$DB_HOST_OVERRIDE" ]; then
    DB_HOST="$DB_HOST_OVERRIDE"
    echo "  DB primary: $DB_HOST (manual override)"
elif $IS_PRIMARY; then
    DB_HOST="host.docker.internal"
    echo "  DB primary: THIS machine (host.docker.internal)"
    echo "  Other machines should use: --db-host $TS_IP"
else
    echo ""
    echo "  Which machine hosts postgres/redis?"
    echo "  Options:"
    echo "    1) This machine ($TS_IP) — run with --primary"
    echo "    2) Another machine — enter its Tailscale IP"
    echo ""
    echo "  Tailscale network peers:"
    tailscale status 2>/dev/null | grep -v "^$" | head -10 || true
    echo ""
    read -r -p "  Enter DB host Tailscale IP (or 'self' for this machine): " DB_HOST_INPUT
    case "$DB_HOST_INPUT" in
        self|"$TS_IP"|"") DB_HOST="host.docker.internal"; IS_PRIMARY=true ;;
        *)                 DB_HOST="$DB_HOST_INPUT" ;;
    esac
fi

POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-localdev}"
REDIS_PASSWORD="${REDIS_PASSWORD:-localdev}"

# ─── Write .env.tailscale ─────────────────────────────────────────────────────
echo ""
echo "▸ Writing $ENV_FILE..."
cat > "$ENV_FILE" <<EOF
# MedinovAI Tailscale Configuration — $(date -u)
# Generated by scripts/bootstrap/tailscale-config.sh
# This file is gitignored (machine-specific). Do NOT commit.

TS_IP=$TS_IP
TS_HOSTNAME=$TS_HOSTNAME
IS_PRIMARY=$IS_PRIMARY
DB_HOST=$DB_HOST
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
REDIS_PASSWORD=$REDIS_PASSWORD
DATABASE_URL=postgresql://medinovai:${POSTGRES_PASSWORD}@${DB_HOST}:5432/medinovai
REDIS_URL=redis://:${REDIS_PASSWORD}@${DB_HOST}:6379/0
EOF
echo "  ✓ $ENV_FILE"

# ─── Generate per-machine K8s ConfigMap ───────────────────────────────────────
echo ""
echo "▸ Generating ConfigMap for K8s pods..."
cat > "$OVERLAY_DIR/configmap-env-local.yaml" <<EOF
# Auto-generated by tailscale-config.sh — do NOT edit manually.
# Regenerate with: bash scripts/bootstrap/tailscale-config.sh
apiVersion: v1
kind: ConfigMap
metadata:
  name: medinovai-env
  namespace: medinovai-services
  labels:
    app.kubernetes.io/managed-by: medinovai-deploy
    environment: docker-desktop
    ts-host: "$TS_HOSTNAME"
data:
  NODE_ENV: "development"
  LOG_FORMAT: "json"
  LOG_LEVEL: "debug"
  DATABASE_URL: "postgresql://medinovai:${POSTGRES_PASSWORD}@${DB_HOST}:5432/medinovai"
  REDIS_URL: "redis://:${REDIS_PASSWORD}@${DB_HOST}:6379/0"
  ENVIRONMENT: "docker-desktop"
  TS_IP: "$TS_IP"
  TS_HOSTNAME: "$TS_HOSTNAME"
  IS_PRIMARY: "$IS_PRIMARY"
EOF
echo "  ✓ $OVERLAY_DIR/configmap-env-local.yaml"

# Also write for medinovai-ai namespace
cat > "$OVERLAY_DIR/configmap-env-ai-local.yaml" <<EOF
# Auto-generated by tailscale-config.sh — do NOT edit manually.
apiVersion: v1
kind: ConfigMap
metadata:
  name: medinovai-env
  namespace: medinovai-ai
  labels:
    app.kubernetes.io/managed-by: medinovai-deploy
    environment: docker-desktop
    ts-host: "$TS_HOSTNAME"
data:
  NODE_ENV: "development"
  LOG_FORMAT: "json"
  LOG_LEVEL: "debug"
  DATABASE_URL: "postgresql://medinovai:${POSTGRES_PASSWORD}@${DB_HOST}:5432/medinovai"
  REDIS_URL: "redis://:${REDIS_PASSWORD}@${DB_HOST}:6379/0"
  ENVIRONMENT: "docker-desktop"
  TS_IP: "$TS_IP"
  TS_HOSTNAME: "$TS_HOSTNAME"
EOF
echo "  ✓ $OVERLAY_DIR/configmap-env-ai-local.yaml"

# ─── Summary ─────────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  ✓ Tailscale configuration complete"
echo "║"
echo "║  This machine:  $TS_HOSTNAME ($TS_IP)"
echo "║  DB host:       $DB_HOST"
echo "║  Primary node:  $IS_PRIMARY"
echo "║"
if $IS_PRIMARY; then
    echo "║  On OTHER machines, run:"
    echo "║    bash scripts/bootstrap/tailscale-config.sh --db-host $TS_IP"
fi
echo "║"
echo "║  Next: bash scripts/bootstrap/install-k8s.sh"
echo "╚══════════════════════════════════════════════════════════════╝"
